/**
 * Bakes a seamlessly-tiling 4-ink CMYK rosette screen to a PNG.
 *
 * A rotated dot lattice only tiles if its angle has a rational tangent, so this
 * uses the approximations real RIPs use — C atan(3)=71.57deg, M 45deg,
 * Y atan(1/3)=18.43deg, K 0deg. Each lattice is generated by integer vectors
 * whose sublattice of Z^2 contains (T,0) and (0,T), so all four repeat exactly
 * inside one T x T square.
 *
 *   node scripts/make-rosette.mjs [--tile 60] [--coverage 0.12] [--out path]
 *                                 [--inks process|warm|riso|newsprint|#hex,#hex,#hex,#hex]
 *
 * Zero dependencies: the PNG is encoded here with node's built-in zlib.
 */
import { deflateSync } from "node:zlib";
import { writeFileSync } from "node:fs";

const arg = (name, fallback) => {
    const i = process.argv.indexOf(`--${name}`);
    return i === -1 ? fallback : process.argv[i + 1];
};

const TILE = Number(arg("tile", 60));
const COVERAGE = Number(arg("coverage", 0.12));
const OUT = arg("out", "src/assets/textures/rosette.png");

// Named ink sets. `--inks riso` swaps process CMYK for a warmer duotone-ish
// palette; `--inks` also accepts four comma-separated hex values.
const PALETTES = {
    process: ["#00aeef", "#ec008c", "#fff100", "#000000"],
    warm: ["#3aa8b0", "#e2557a", "#f2c14e", "#241f1c"],
    riso: ["#0078bf", "#ff48b0", "#ffe800", "#3d3d3d"],
    newsprint: ["#7fa8b8", "#c98b8b", "#ded2a8", "#1c1a17"],
};
const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const inkArg = arg("inks", "process");
const PALETTE = (
    PALETTES[inkArg] ?? inkArg.split(",").map((c) => c.trim())
).map(hex);
const SS = 4; // supersample factor — the dots are ~3px across, so they need it

// Generating vectors per ink. `u` and its perpendicular define the lattice;
// each period divides TILE, which is what makes the tile seamless.
// Pitches land within ~12% of each other (2.83–3.16px at TILE=60), close
// enough to read as one screen ruling.
const INKS = [
    // [name, ux, uy, misregistration offset in px] — colour comes from PALETTE
    ["cyan",    1,  3, [ 0.25, -0.15]],
    ["magenta", 2,  2, [-0.20,  0.22]],
    ["yellow",  3,  1, [ 0.18,  0.20]],
    ["black",   3,  0, [-0.12, -0.10]],
].map(([name, ux, uy, off], i) => [name, ux, uy, PALETTE[i], off]);

const W = TILE * SS;
const acc = new Float64Array(W * W * 3).fill(1); // subtractive, on white paper

for (const [, ux, uy, rgb, [ox, oy]] of INKS) {
    const pitch = Math.hypot(ux, uy);
    const radius = Math.sqrt(COVERAGE / Math.PI) * pitch * SS;
    const vx = -uy, vy = ux; // perpendicular generator
    const det = ux * vy - uy * vx; // = ux^2 + uy^2

    // Coverage mask for this ink across the supersampled tile.
    const cov = new Float64Array(W * W);
    for (let y = 0; y < W; y++) {
        for (let x = 0; x < W; x++) {
            // Position relative to the nearest lattice point: solve
            // (px,py) = a*u + b*v in lattice units, round, subtract.
            const px = (x + 0.5) / SS - ox;
            const py = (y + 0.5) / SS - oy;
            const a = (px * vy - py * vx) / det;
            const b = (ux * py - uy * px) / det;
            const da = a - Math.round(a);
            const db = b - Math.round(b);
            const dx = (da * ux + db * vx) * SS;
            const dy = (da * uy + db * vy) * SS;
            cov[y * W + x] = Math.hypot(dx, dy) <= radius ? 1 : 0;
        }
    }

    // Each ink absorbs its complement: multiply the paper by (1 - ink*coverage).
    const ink = rgb.map((c) => c / 255);
    for (let i = 0; i < W * W; i++) {
        const c = cov[i];
        if (!c) continue;
        for (let ch = 0; ch < 3; ch++) {
            acc[i * 3 + ch] *= 1 - c * (1 - ink[ch]);
        }
    }
}

// Box-downsample the supersampled buffer to TILE x TILE.
const px = Buffer.alloc(TILE * TILE * 3);
for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < TILE; x++) {
        for (let ch = 0; ch < 3; ch++) {
            let sum = 0;
            for (let sy = 0; sy < SS; sy++) {
                for (let sx = 0; sx < SS; sx++) {
                    sum += acc[((y * SS + sy) * W + (x * SS + sx)) * 3 + ch];
                }
            }
            px[(y * TILE + x) * 3 + ch] = Math.round((sum / (SS * SS)) * 255);
        }
    }
}

/* ---------------- minimal PNG encoder (RGB8, filter 0) ---------------- */
const CRC = (() => {
    const t = new Int32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
        t[n] = c;
    }
    return t;
})();
const crc32 = (buf) => {
    let c = -1;
    for (const b of buf) c = CRC[(c ^ b) & 0xff] ^ (c >>> 8);
    return (c ^ -1) >>> 0;
};
const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(body));
    return Buffer.concat([len, body, crc]);
};

const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(TILE, 0);
ihdr.writeUInt32BE(TILE, 4);
ihdr[8] = 8;  // bit depth
ihdr[9] = 2;  // colour type: truecolour
const raw = Buffer.alloc(TILE * (TILE * 3 + 1));
for (let y = 0; y < TILE; y++) {
    raw[y * (TILE * 3 + 1)] = 0; // filter: none
    px.copy(raw, y * (TILE * 3 + 1) + 1, y * TILE * 3, (y + 1) * TILE * 3);
}
writeFileSync(
    OUT,
    Buffer.concat([
        Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
        chunk("IHDR", ihdr),
        chunk("IDAT", deflateSync(raw, { level: 9 })),
        chunk("IEND", Buffer.alloc(0)),
    ]),
);

const pitches = INKS.map(([n, ux, uy]) => `${n} ${Math.hypot(ux, uy).toFixed(2)}px`);
console.log(
    `${OUT} — ${TILE}x${TILE}, inks ${inkArg}, coverage ${COVERAGE}, pitches: ${pitches.join(", ")}`,
);
